language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  # PyPy versions
  - "pypy3"

install:
  - pip install -r requirements.txt  # command to install dependencies

# command to run tests
before_script: cd application/tests
script: python3 -m unittest discover application/tests